language: node_js
sudo: false
node_js:
  - "8"
cache: yarn
before_script: yarn global add codecov
script:
  - yarn lint
  - yarn test --coverage --maxWorkers=4
  - yarn build
after_success:
  - codecov
